# Generated by Django 4.0.4 on 2022-05-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0002_art_project_delete_file_delete_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_project',
            name='pdf',
            field=models.FileField(upload_to='art/img'),
        ),
    ]
