# Generated by Django 4.0.4 on 2022-05-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0003_alter_art_project_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art_project',
            old_name='pdf',
            new_name='img',
        ),
    ]
