# Generated by Django 4.0.4 on 2022-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0004_rename_pdf_art_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art_project',
            name='img',
            field=models.ImageField(upload_to='art/img'),
        ),
    ]
