# Generated by Django 4.0.4 on 2022-05-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0005_alter_art_project_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art_project',
            new_name='ArtProject',
        ),
    ]
