# Generated by Django 4.0.4 on 2022-06-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0006_rename_art_project_artproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artproject',
            name='title',
        ),
    ]
