# Generated by Django 4.0.4 on 2022-06-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego', '0009_pdffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='img',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='pdf',
            field=models.FileField(default='defualtname', upload_to='art/pdf'),
            preserve_default=False,
        ),
    ]
